name: dubbuck_front
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.9
  fluttertoast: ^8.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^17.1.2
  photo_view: ^0.15.0
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.1
  table_calendar: ^3.0.9
  path_provider: ^2.0.11
  get_it: ^7.2.0
  dio: ^5.4.3+1
  uuid: ^4.3.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  geocoding: ^3.0.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  flutter_naver_login: ^1.8.0
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  firebase_app_check: ^0.2.2+5
  url_launcher: ^6.2.6
  uni_links2: ^0.6.0+2
  kakao_flutter_sdk_user: ^1.9.1+2
  collection: ^1.18.0
  csv: ^6.0.0
  flutter_polyline_points: ^2.0.0
  proj4dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator: ^2.0.1
  skeletons: ^0.0.3
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  geolocator: ^11.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/chat/
    - assets/splash/
    - assets/weather/
    - assets/ranking/
    - assets/login/
    - lib/i18n/
    - assets/출석체크.gif